### ISSUE TITLE
Update server url and key via python script in stream section of OBS 

### ISSUE THREAD

**Issue by MohdIrfan12** [upgradeQ/OBS-Studio-Python-Scripting-Cheatsheet-obspython-Examples-of-API#29]
Is it possible to update OBS stream section via scripts? So let's say there is a python script that is somehow setting Stream configurations(RTMP URL and Stream key) programmatically and this script will run on OBS startup. Is it possible?
<img width="1041" alt="Screenshot 2022-01-23 at 12 37 37 PM" src="https://user-images.githubusercontent.com/27348106/150668383-511e2089-208e-4350-83f0-33947d274431.png">

**Comment by upgradeQ** [comment]
It might be possible to do it from `obspyton`/`obslua`. The Stream tab in OBS Studio Settings UI uses so called `obs_service_t` structure which you can obtain from `obs_frontend_get_streaming_service` call, you might consult [`Service API Reference`](https://obsproject.com/docs/reference-services.html) for details.
While writing this post, I found [this](https://github.com/ssbm-oro/alttpr-league-obs) related to question repo in GitHub Search. My only concern is that there might be  1  memory leak, because there are no "*_release" API available for `obs_service_t`
