### ISSUE TITLE
some examples is not available, is it true ? or i make some mistake

### ISSUE THREAD

**Issue by Kevin-Kevin** [upgradeQ/OBS-Studio-Python-Scripting-Cheatsheet-obspython-Examples-of-API#34]
like src/change_order.py
this file can not run sucessfully
cause `obs_scene_enum_items()` 's arguments not correct(wasting a lot of my time😔）

**Comment by MarioMey** [comment]
If you are using these examples, you are learning. In learning, you don't waste your time... you use it. Some things take longer than others.

I used a lot of my time to learn using Python in OBS... A LOT. 

Maybe my repository is usefull for you: https://github.com/MarioMey/obs-osc-pythonscript. It has a lot of commands ready to use... or ready to learn from. But now, I can't help you, I don't use it since pandemic. I don't even have this code installed in my system.

**Comment by upgradeQ** [comment]
```python
@contextmanager
def scene_enum(items): # _scene
    items = S.obs_scene_enum_items(items) # _scene
    try:
        yield items
    finally:
        S.sceneitem_list_release(items)     
```
There is indeed a problem with this code, argument should be named `_scene` and not `items`. I did test on the  original script and it worked no crashes or memory leaks. I'll update the confusing line later.

**Comment by upgradeQ** [comment]
I've changed the code, should be more clear. I will close the issue now, but if you have any questions or suggestions feel free to reopen it again( regarding that example).
