### ISSUE TITLE
[query] Which is better to use...?

### ISSUE THREAD

**Issue by MarioMey** [upgradeQ/OBS-Studio-Python-Scripting-Cheatsheet-obspython-Examples-of-API#4]
Seeing [change_order.py](https://github.com/upgradeQ/OBS-Studio-Python-Scripting-Cheatsheet-obspython-Examples-of-API/blob/master/src/change_order.py), I realized that you used `@contextmanager` functions to use `with` statement. You didn't use them in other scripts. I would like to know why you used it. Is it better? Does it close automatically the reference or something like that?

Another question: can I ask this queries here? 😁

**Comment by upgradeQ** [comment]
@MarioMey I've used context managers a lot in [Scripted-text](https://github.com/upgradeQ/Scripted-text). Yes, yes as soon as its leaves closure. 
You might also want to use [`ExitStack`](https://docs.python.org/3/library/contextlib.html#contextlib.ExitStack) since it can select context mangers based on condition. It also reduces nesting level e.g consider [this](https://github.com/upgradeQ/Scripted-text/blob/5f9ecd8cb25687b27a9db830ab06f65573f46b14/scripted_text.py#L328-L346) code:
```python
def sanic_effect(self):
    "really fast speed text scrolling(filter)"
    # add filter scroll to source if not present,
    self.update_text(self._scripted_text)
    with source_ar(self.source_name) as source, filter_ar(
        source, "py_scroll"
    ) as scroll:
        if scroll is None:
            with data_ar() as settings:
                obs.obs_data_set_int(settings, "speed_x", 5000)
                with p_source_ar("scroll_filter", "py_scroll", settings) as _source:
                    obs.obs_source_filter_add(source, _source)

        with data_ar(scroll) as filter_settings:
            obs.obs_data_set_int(filter_settings, "speed_x", 5000)
            obs.obs_source_update(scroll, filter_settings)
            if self.duration // self.refresh_rate <= 3:
                obs.obs_source_filter_remove(source, scroll)
                self.duration = 0
```
Using [`ExitStack`](https://docs.python.org/3/library/contextlib.html#contextlib.ExitStack)  *unreleased version*
```python
def sanic_effect(self):
    "really fast speed text scrolling(filter)"
    # add filter scroll to source if not present,
    self.update_text(self._scripted_text)
    with ExitStack() as stack:
        source = stack.enter_context(source_ar(self.source_name))
        scroll = stack.enter_context(filter_ar(source, "py_scroll"))
        if scroll is None:
            settings = stack.enter_context(data_ar())
            obs.obs_data_set_int(settings, "speed_x", 5000)
            _source = stack.enter_context(
                p_source_ar("scroll_filter", "py_scroll", settings)
            )
            obs.obs_source_filter_add(source, _source)
        filter_settings = stack.enter_context(data_ar(scroll))
        obs.obs_data_set_int(filter_settings, "speed_x", 5000)
        obs.obs_source_update(scroll, filter_settings)
        if self.duration // self.refresh_rate <= 3:
            obs.obs_source_filter_remove(source, scroll)
            self.duration = 0
```
Sure, I think we can try using [`Discussions`](https://github.com/upgradeQ/OBS-Studio-Python-Scripting-Cheatsheet-obspython-Examples-of-API/discussions/5)
